services:
- type: web
  name: typesense
  runtime: docker
  repo: https://github.com/kezios/typesense-render-blueprint
  plan: starter
  healthCheckPath: /health
  disk:
    name: typesense-data
    mountPath: /typesense-data
    sizeGB: 1  
  envVars:
  - key: TYPESENSE_API_KEY
    value: "7AZaGfx8toKDewS5jn1iSwZcn/PCi7m5i2HI8KFeYYM="
  - key: TYPESENSE_DATA_DIR
    value: /typesense-data
  - key: TYPESENSE_ENABLE_CORS
    value: "true"